### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'execute_script'

### ISSUE THREAD

**Issue by Ashrafmdmatin41** [nuhmanpk/WebScrapper#23]
Screenshot + Screenrecord not working

**Comment by nuhmanpk** [comment]
Thanks @Ashrafmdmatin41  for bringing this issue to my attention. I appreciate you taking the time to report that the screenshot and screen recording functionality is currently not working as expected.

The current implementation using a headless browser does have limitations, especially when it comes to cloud-based environments. I'm working on better approach that can overcome the current limitations

**Comment by Ashrafmdmatin41** [comment]
Okk bruhh waiting
