### ISSUE TITLE
Not Working Crawl Complete Web

### ISSUE THREAD

**Issue by King-Nomis** [nuhmanpk/WebScrapper#28]
![Uploading Screenshot_2024-12-20-07-54-32-113.jpeg…]()

**Comment by nuhmanpk** [comment]
@King-Nomis ,  The screenshot you provided does not seem to be working for me. Could you please provide more details or clarify the issue?

**Comment by King-Nomis** [comment]
> @King-Nomis , The screenshot you provided does not seem to be working for me. Could you please provide more details or clarify the issue?

Screenshot 
![Screenshot_2024-12-20-07-54-32-113](https://github.com/user-attachments/assets/672a98bd-9267-4fce-a5d4-9f5b3a9dcf8f)

Log id mang rha  hai . Jabki repo me kahi log id variable hai hi nhi

**Comment by nuhmanpk** [comment]
Could you provide a channel id , to dump the crawling data

**Comment by nuhmanpk** [comment]
Add your channel link [here](https://github.com/nuhmanpk/WebScrapper/blob/8154df5956a37b9e143051365f91938641be9184/main.py#L38) , use jsonInfo bot to get channel ID from telegram. Or else you could change the code to send the crawl data directly your chat

**Comment by King-Nomis** [comment]
Thanks I get it 😀
